

version: 2

models:
  - name: partido_ganador_provincia
    description: "Partido ganador por provincia"
    columns:
      - name: provincia
        description: "Provincia"
        tests:
          - not_null
          - unique
      - name: partido_ganador
        description: "Nombre del partido ganador"
        tests:
          - not_null
      - name: cantidad_votos
        description: "Cantidad de votos obtenidos"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"

  - name: top_5_nacional
    description: "Top 5 partidos a nivel nacional"
    columns:
      - name: ranking
        description: "Posición en el ranking"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "between 1 and 5"
      - name: partido
        description: "Nombre del partido"
        tests:
          - not_null
      - name: total_votos
        description: "Total de votos obtenidos"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"

  - name: participacion_etaria
    description: "Participación electoral por franja etaria"
    columns:
      - name: rango_edad
        description: "Rango de edad"
        tests:
          - not_null
          - accepted_values:
              values: ['18-25', '26-40', '41-60', '60+']
      - name: cantidad_votantes
        description: "Cantidad de votantes en el rango"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
      - name: porcentaje_participacion
        description: "Porcentaje de participación"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "between 0 and 100"