version: 2

models:
  - name: ranking_politicos
    description: "Ranking de políticos por cantidad de votos en cada elección"
    columns:
      - name: id_eleccion
        data_tests:
          - not_null
      - name: politico
        data_tests:
          - not_null
      - name: votos_recibidos
        data_tests:
          - not_null

  - name: porcentaje_votos_blanco
    description: "Porcentaje de votos en blanco por elección legislativa"
    columns:
      - name: id_eleccion
        data_tests:
          - not_null
      - name: pct_votos_blanco
        data_tests:
          - not_null
          - expression_is_true:
              expression: "pct_votos_blanco >= 0 and pct_votos_blanco <= 100"

  - name: porcentaje_respuestas_por_cp
    description: "% de cada respuesta en consultas populares"
    columns:
      - name: id_eleccion
        data_tests:
          - not_null
      - name: id_opcion
        data_tests:
          - not_null
      - name: pct_respuesta
        data_tests:
          - not_null
          - expression_is_true:
              expression: "pct_respuesta >= 0 and pct_respuesta <= 100"

  - name: ganador_consulta
    description: "Opción ganadora en cada consulta popular"
    columns:
      - name: id_eleccion
        data_tests:
          - not_null
          - unique
      - name: ganador_opcion
        data_tests:
          - not_null