version: 2

sources:
  - name: raw_election_data
    database: election_db
    schema: raw
    tables:
      - name: raw_results
        description: "Resultados electorales por centro de votación"
        columns:
          - name: id_resultado
            description: "Identificador único del resultado"
            tests:
              - unique
              - not_null
          - name: id_centro
            description: "ID del centro de votación"
          - name: id_partido
            description: "ID del partido político"
          - name: cantidad_votos
            description: "Cantidad de votos obtenidos"
          - name: fecha_eleccion
            description: "Fecha de la elección"

      - name: raw_parties
        description: "Información de partidos políticos"
        columns:
          - name: id_partido
            description: "Identificador único del partido"
            tests:
              - unique
              - not_null
          - name: nombre_partido
            description: "Nombre del partido político"
          - name: sigla
            description: "Sigla del partido"

      - name: raw_voters
        description: "Información de electores"
        columns:
          - name: id_elector
            description: "Identificador único del elector"
            tests:
              - unique
              - not_null
          - name: fecha_nacimiento
            description: "Fecha de nacimiento del elector"
          - name: provincia
            description: "Provincia de residencia"
          - name: centro_votacion
            description: "Centro de votación asignado"