version: 2

sources:
  - name: electoral_db
    schema: public
    tables:
      - name: voto
      - name: voto_eleccion_legislativa
      - name: voto_consulta_popular
      - name: voto_elije_opcion_respuesta   
      - name: politico
      - name: politico_eleccion_pertenece_partido
      - name: opcion_respuesta
      - name: cp_tiene_opcion_respuesta